baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Nathan Buache'
theme="archie"
copyright = "© Nathan B."
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="auto"
	useCDN=false
	subtitle = "Hello there! 👋🏻 "

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/nthnbch"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://twitter.com/athulcajay/"

[[params.social]]
name = "GDR"
icon = "heart"
url = "https://twitter.com/athulcajay/"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://twitter.com/athulcajay/"

[[params.social]]
name = "Facebook"
icon = "facebook"
url = "https://gitlab.com/athul/"

[[params.social]]
name = "QoQa"
icon = "user-check"
url = "https://gitlab.com/athul/"

[[params.social]]
name = "Mail"
icon = "inbox"
url = "https://github.com/nthnbch"

[[params.social]]
name = "Spotify"
icon = "disc"
url = "https://gitlab.com/athul/"

[[params.social]]
name = "Discord"
icon = "mic"
url = "https://github.com/nthnbch"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3