baseURL = "https://nathan.swiss/"
languageCode = "en-US"
theme = "hugo-white-paper-theme"
themesDir = "themes"
title = "Nathan Buache"
[pagination]
  pagerSize = 10
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = "G-FFR91K2J2Y"
  twitter_handle = ""
  showAuthorOnHomepage = false
  showAuthorOnPosts = false
  showIntroContentOnHomepage = true
  showPostsOnHomepage = false
  usePaginationOnHomepage = false
  limitPostsOnHomepage = 1 # only used if usePaginationOnHomepage is false
  sortPostsByDateOldestFirst = false
  addDot = true
  addFrame = false  # Removed frame for modern look
  highlightColor = '#6750a4'
  baseColor = "#fdfbff"
  baseOffsetColor = "#f7f2fa"
  headingColor = "#1c1b1f"
  textColor = "#49454f"
  dotColor = "#6750a4"
  enableGoogleFonts = true 
  googleFontsUrl = "https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Roboto+Mono:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap"
  fontFamilyHeading = "Roboto"
  fontFamilyParagraph = "Roboto"
  fontFamilyMonospace = "Roboto Mono"

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = "Blog"
    identifier = "posts"
    weight = 2
    url = "/posts/"
  [[menu.main]]
    name = "About"
    identifier = "about"
    weight = 3
    url = "/about/"
  [[menu.main]]
    name = "Projects"
    identifier = "projects"
    weight = 4
    url = "/projects/"