baseURL = "https://nathan.swiss/"
languageCode = "en-US"
theme = "hugo-white-paper-theme"
themesDir = "themes"
title = "nathan.swiss"
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Disable taxonomies (tags, categories) completely
disableKinds = ["taxonomy", "term"]

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = "G-FFR91K2J2Y"
  showIntroContentOnHomepage = true
  showPostsOnHomepage = false
  homePageSubtitle = "Nathan Buache - Test Manager - QA Specialist in Lausanne Swiss"
  # Typography and Design
  highlightColor = '#000000'
  baseColor = "#fdfbff"
  baseOffsetColor = "#f7f2fa"
  headingColor = "#1c1b1f"
  textColor = "#49454f"
  enableGoogleFonts = true 
  googleFontsUrl = "https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&family=UnifrakturCook:wght@700&display=swap"
  fontFamilyHeading = "UnifrakturCook"
  fontFamilyParagraph = "Inter"
  fontFamilyMonospace = "Inter"

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    name = "Blog"
    identifier = "posts"
    weight = 1
    url = "/posts/"
  [[menu.main]]
    name = "About"
    identifier = "about"
    weight = 2
    url = "/about/"
  [[menu.main]]
    name = "Projects"
    identifier = "projects"
    weight = 3
    url = "/projects/"