baseURL = 'https://nathan.swiss/'
languageCode = 'en-us'
title = 'Nathan Buache'
theme="archie"
copyright = ""
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="light"
	useCDN=false
	subtitle = "Hello there! 👋🏻 I'm Nathan. You'll find here: social links, a short bio and some of my posts. Enjoy "

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/nthnbch"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/nathanbuache/"

[[params.social]]
name = "GDR"
icon = "heart"
url = "https://gfolk.me/nthnbch"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://www.instagram.com/nthnbch/"

[[params.social]]
name = "Facebook"
icon = "facebook"
url = "https://www.facebook.com/nthnbch"

[[params.social]]
name = "QoQa"
icon = "user-check"
url = "https://www.qoqa.ch/fr/posts/5275"

[[params.social]]
name = "Mail"
icon = "inbox"
url = "mailto:nathan@buache.com"

[[params.social]]
name = "Spotify"
icon = "disc"
url = "https://open.spotify.com/user/jo_margo?si=43630b796d6a462a"

[[params.social]]
name = "Discord"
icon = "mic"
url = "https://discordapp.com/users/773992583286226973"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3