baseURL = "https://example.com/"
languageCode = "en-US"
theme = "hugo-white-paper-theme"
title = "Hugo White Paper Theme"

[params]
  showAuthorOnHomepage = false
  showAuthorOnPosts = false
  showIntroContentOnHomepage = true
  showPostsOnHomepage = true
  usePaginationOnHomepage = false
  limitPostsOnHomepage = 3
  sortPostsByDateOldestFirst = false
  addDot = true
  addFrame = false
  highlightColor = '#000000'
  baseColor = "#fdfbff"
  baseOffsetColor = "#f7f2fa"
  headingColor = "#1c1b1f"
  textColor = "#49454f"
  dotColor = "#000000"
  enableGoogleFonts = true 
  googleFontsUrl = "https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&family=UnifrakturCook:wght@700&display=swap"
  fontFamilyHeading = "UnifrakturCook"
  fontFamilyParagraph = "Inter"
  fontFamilyMonospace = "Inter"

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = "Blog"
    identifier = "posts"
    weight = 2
    url = "/posts/"
  [[menu.main]]
    name = "About"
    identifier = "about"
    weight = 3
    url = "/about/"
